title: gcpvalidate
description: "Client-side validation of Google Cloud resource identifiers and attributes for Go applications, based on documented conventions (not affiliated with Google)."

remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
  - jekyll-remote-theme

# External navigation links
nav_external_links:
  - title: gcpvalidate on GitHub
    url: https://github.com/UnitVectorY-Labs/gcpvalidate

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/UnitVectorY-Labs/gcpvalidate"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree"